#!/usr/bin/env python3
import os
import re
from pathlib import Path

README_PATH = Path(os.environ.get("README_PATH", "README.md"))
PROFILE_DIRECTORY = Path("profile")
IMAGE_REFERENCES = {
    "Terry's GitHub Stats": Path(
        os.environ.get("STATS_CARD_PATH", "profile/stats.svg")
    ),
    "Top Languages": Path(
        os.environ.get("TOP_LANGUAGES_CARD_PATH", "profile/top-langs.svg")
    ),
}
VERSIONED_IMAGE_PATTERN = re.compile(r"^(?:stats|top-langs)(?:-\d+-\d+)?\.svg$")


def replace_image_reference(
    readme_text: str,
    image_alt_text: str,
    new_image_path: Path,
) -> tuple[str, Path]:
    """Replace a README image reference and return its previous local path.

    Args:
        readme_text: Current README content.
        image_alt_text: Markdown alternative text identifying the image.
        new_image_path: Newly generated image path.

    Returns:
        Updated README content and the previous image path.

    Raises:
        RuntimeError: If the expected image reference is missing.
    """
    pattern = re.compile(
        rf"(!\[{re.escape(image_alt_text)}\]\()([^)?]+)(?:\?[^)]*)?(\))"
    )
    match = pattern.search(readme_text)
    if match is None:
        raise RuntimeError(f"Could not find image '{image_alt_text}' in {README_PATH}.")

    markdown_path = f"./{new_image_path.as_posix().removeprefix('./')}"
    updated_text, replacement_count = pattern.subn(
        rf"\g<1>{markdown_path}\g<3>",
        readme_text,
        count=1,
    )
    if replacement_count != 1:
        raise RuntimeError(
            f"Could not update image '{image_alt_text}' in {README_PATH}."
        )

    previous_path = Path(match.group(2).removeprefix("./"))
    return updated_text, previous_path


def remove_previous_image(previous_path: Path, current_path: Path) -> None:
    """Delete a superseded generated image within the profile directory.

    Args:
        previous_path: Image path referenced before the README update.
        current_path: Image path generated by the current workflow run.
    """
    if previous_path == current_path or not previous_path.exists():
        return

    expected_directory = PROFILE_DIRECTORY.resolve()
    if (
        previous_path.resolve().parent != expected_directory
        or VERSIONED_IMAGE_PATTERN.fullmatch(previous_path.name) is None
    ):
        raise RuntimeError(f"Refusing to delete unexpected image path: {previous_path}")

    previous_path.unlink()
    print(f"Removed previous image {previous_path}.")


def main() -> None:
    """Update README image paths and remove superseded generated images."""
    readme_text = README_PATH.read_text(encoding="utf-8")
    previous_images: list[tuple[Path, Path]] = []

    for image_alt_text, current_path in IMAGE_REFERENCES.items():
        readme_text, previous_path = replace_image_reference(
            readme_text,
            image_alt_text,
            current_path,
        )
        previous_images.append((previous_path, current_path))

    README_PATH.write_text(readme_text, encoding="utf-8", newline="\n")

    for previous_path, current_path in previous_images:
        remove_previous_image(previous_path, current_path)

    print("Updated README image references.")


if __name__ == "__main__":
    main()
